config/routes.rb
Dc3::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"

  resources :oauth , :controller => 'oauth' do
    collection do
      get :start
      match :callback
      get :friends
    end
  end

  resources :upload , :controller => 'upload' do
    collection do
      get :index
      post :file
      get :complete
    end
  end

  get "sections/create"

  get "home/index"
  get "home/thanks"
  get "home/destroy"
  get "home/ajaxrandom"
  get "home/ajaxpopular"
  get "home/ajaxmyvideos"
  get "home/ajaxfreindvideos"
  get "home/section"
  get "home/createvideo"
  get "home/locale/:locale"   => "home#locale", :as => 'set_locale'

  match "/home/updatesession/:user_id"            => "home#updatesession", :as => 'updatesession'

  get "users/banned"

  get "webcam/new"
  match "webcam/submit"
  match "webcam/recorder/:track_id"               => 'webcam#recorder',    :as =>'webcam_recorder'
  match "webcam/nocamera"                         => 'webcam#nocamera',    :as =>'nocamera'
  match "webcam/deniedcamera"                     => 'webcam#deniedcamera',    :as =>'deniedcamera'
  
  match "/vid"              => "home#index", :as => 'random_video'
  match "/vid/:id"          => "home#index", :as => 'single_video'
  match "/vid/:ida/:idb"    => "home#index", :as => 'double_video'
  match "/mobile"           => 'home#mobile', :as => 'mobile'
  match "/home/reloadbattle(/:video_id)(/:autoplay)" => 'home#reloadbattle', :as => 'home/reloadbattle'

  match "/share/:id"      => "videos#share", :as => 'share_video'

  match "/info/rules"     => "home#rules", :as => 'rules'
  match "/info/faq"       => "home#faq", :as => 'faq'
  match "/info/terms"       => "home#terms", :as => 'terms'
  
  match "/tab/xbox(/:locale)"  => "tab#xbox", :as => 'tab_xbox'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :votes
  resources :tracks

  match "/users/getUserinfo/:user_id"       => "users#getUserinfo", :as => 'getUserinfo'

  resources :videos

  match "/video/uploadform"       => "videos#uploadform", :as => 'uploadform'

  match "/video/vote/:id" => "videos#vote", :as => 'video_vote'

  root  :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @locale = Locale.all
    video_one ||=(params[:id] || params[:ida]) || nil
    video_two ||=params[:idb] || nil
    @track = Track

    
    @battle = Video.battle(video_one, video_two)

    # tabs
    @list_latest = Video.list_latest
    @list_popular = Video.video_popular
    @is_winner = Video.is_winner
    @list_winner = Video.list_winner


    # puts "WINNER ************************************"
    # puts @is_winner.count
    # puts @list_winner
    # puts "WINNER ************************************"

    if session[:user_id] and User.find_by_fb_id(session[:user_id])

      # puts '-----++++++++++++++'
      # puts session[:user_id]
      # puts '-----++++++++++++++'

      @user = User.find_by_fb_id(session[:user_id])

      @my_videos = @list_latest.select {|i| i.user_id == @user.id }

      #    # check token expiration and request new if needed!
      #    fb_auth = FbGraph::Auth.new('151259104968742', '2e783d93aefa6581e923a62c6054abac')
      #    fb_auth.client # => Rack::OAuth2::Client

      #    # get Facebook's auth cookie in advance using their JS SDK
      #    fb_auth.from_cookie(cookies)
      #    # fb_auth.access_token # => Rack::OAuth2::AccessToken
      #    # fb_auth.user         # => FbGraph::User (only basic attributes)
      #    # fb_auth.user.fetch   # => fetch more details

      #    puts "/*/*/*/*/*/*/*/*/*/*/*/*/*"
      #    puts fb_auth.access_token
      #    puts "/*/*/*/*/*/*/*/*/*/*/*/*/*"

      #    ##try this, rather than getting the user again
      #    # fbuser = fb_auth.user

      fbuser = FbGraph::User.me(@user.usertoken).fetch
      friends = fbuser.friends

      friend_ids = []
      friends.each do |f|
        friend_ids << f.identifier
      end

      @friendvideos = []

      #current_user_friends = User.find_all_by_fb_id(friend_ids)
      current_user_friends = User.where(:fb_id => friend_ids, :banned => false)

      current_user_friends.each do |f|
        @friendvideos << Video.find_by_user_id(f.id)
      end
    else
      # puts '*************************'
      # puts "no session or no user?"
      # puts '*************************'
      @update = true
    end
  end

  ### mobile
  def mobile
    render :layout => "mobile"
  end

  ### destroy session
  def updatesession
    session[:user_id] = params[:user_id]

    # TODO: query user, get friends etc... then update view with content
    # puts "UPDATING .................."
    # puts params[:user_id]
    # puts session[:user_id]
    # puts "UPDATING .................."

    render :json => {:success=>true}
  end

  def destroy
    # Remove the user id from the session
    session[:user_id] = nil
    session[:locale] = nil

    puts "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    puts session.inspect
    puts "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    redirect_to root_url
  end

  ### change locale
  def locale
    locales =  Locale.all
    # make sure locale param is an acceptable locale
    session[:locale] = (locales.has_key?(params[:locale].to_sym)) ? params[:locale] : 'en_US'
    puts "-------------------------------------------"
    puts session[:locale]
    puts "-------------------------------------------"
    redirect_to root_url
  end
  ### ajax request partials

  def reloadbattle
    @auto_play = false
    
    if params[:autoplay]
      @auto_play = true
    end
    # puts "AUTOPLAY -------------"
    # puts @auto_play
    # puts "AUTOPLAY -------------"

    respond_to do |format|
      @user = User.find_by_fb_id(session[:user_id])
      @battle = Video.battle(params[:video_id],nil)
      format.html {
        render :partial => 'shared/videobattle', :layout => false, :locals => { :auto_play => @auto_play, :videos => @battle, :flag => true }
      }
      format.js { render action: "reloadbattle", script: true, :locals => { :auto_play => @auto_play} }
    end
  end

  def ajaxrandom
    respond_to do |format|
      list = Video.list_latest
      @list_random = list.sort_by { rand }
      format.html {
        render   :partial => 'shared/videolist', :layout => false, :locals => { :videos => @list_random, :flag => false }
      }
      format.js {
       render action: "ajaxrandom", script: true
      }
    end
  end

  def ajaxpopular
    respond_to do |format|
      @popular = Video.video_popular
      puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
      puts @popular
      puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"      
      format.html {
        render :partial => 'shared/videolist', :layout => false, :locals => { :videos => @popular, :flag => false }
      }
      format.js {
       render action: "ajaxpopular", script: true
      }
    end
  end

  def ajaxmyvideos
    respond_to do |format|
      user = User.find_by_fb_id(session[:user_id])
      @my_videos = user.videos.where(:status => 'approved');
      puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
      puts @my_videos
      puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
      
      format.html {
        render :partial => 'shared/videolist', :layout => false, :locals => { :videos => @my_videos, :flag => false }
      }
      format.js {
       render action: "ajaxmyvideos", script: true
      }
    end
  end

  def ajaxfreindvideos
    @user = User.find_by_fb_id(session[:user_id])
    fbuser = FbGraph::User.me(@user.usertoken).fetch
    friends = fbuser.friends
    friend_ids = []
    friends.each do |f|
      friend_ids << f.identifier
    end
    @friendvideos = []
    current_user_friends = User.where(:fb_id => friend_ids)
    current_user_friends.each do |f|
      #@friendvideos << Video.find_by_user_id(f.id)
      videoset = Video.where(:user_id => f.id, :status => 'approved')
      videoset.each do |robocop|
        @friendvideos << robocop
      end
    end
    pp "/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/**/*/*/*/*/*/*/*/*/"
    pp @friendvideos
    pp "/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/**/*/*/*/*/*/*/*/*/"

    respond_to do |format|
      format.html {
        render :partial => 'shared/videolist',     :layout => false, :locals => { :videos => @friendvideos, :flag => false }
      }
      format.js {
       render action: "ajaxfriendvideos", script: true
      }
    end
  end

  def createvideo
    if session[:user_id]
      @user = User.find_by_fb_id(session[:user_id])
    else
      # puts '/*/*/*/*/*'
      # puts "no session??"
      # puts '/*/*/*/*/*'
    end
  end


  def thanks
    #render :partial => 'home/thanks', :layout => false
    respond_to do |format|
      format.html {
        render :partial => 'home/thanks'
      }
      format.js {
        render :partial => 'home/thanks',     :layout => false
      }
    end    
  end

  def rules
  end

  def faq
  end

  def terms
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_thanks.html.erb
<div class="thanks-message">
  <aside class="wiz-left">
    <h1><%= t :thanks_title %></h1>
    <p><%= t :thanks_text %></p>

    <div class="thx-social-btns">
      <a href="#" onclick='postToFeedApp(); return false;' class="share-btns fb-btn"><%= t :share_text %></a>
      <a href="//twitter.com/intent/tweet?text=<%= t :twitter_copy %>%20&lt;http://bit.ly.com&gt;" class="share-btns tw-btn"><%= t :share_text %></a>
    </div>
    <a href="/" class="thx-btns"><%= t :thanks_return_home %></a>
  </aside>

  <aside class="wiz-right">
    <div id="thanksTarget"></div>
    <script type="text/javascript">
      jwplayer('thanksTarget').setup({
        'flashplayer': '/player/player.swf',
        'id': 'thanksVid',
        'class': 'thanksVid',
        'width': '480',
        'height': '270',
        'allowFullscreen': false,
        'streamer':'rtmp://roundhousecdn.influxis.com/emgklovf/dc3/streams/_definst_/',
        'file': 'usher-submission-thanks.flv',
        'autostart': 'true',
        //'image': 'http://emgklovf.rtmphost.com/http/thumbnail_play/thumbplay_4702118931945570673.png',
        'skin': '/player/skins/glow.zip'
      });
    </script>    
    <!--
    <object id="thanksplayer" type="application/x-shockwave-flash" data="http://infxapps.influxis.com/apps/ftn53bqfw7wch7owotk0/InfluxisPlayer_20120924181951/InfluxisPlayer.swf" width="480" height="270">
      <param name="movie" value="http://infxapps.influxis.com/apps/ftn53bqfw7wch7owotk0/InfluxisPlayer_20120924181951/InfluxisPlayer.swf"></param>
      <param name="allowFullScreen" value="true"></param>
      <param name="allowScriptAccess" value="always"></param>
      <param name="wmode" value="opaque"></param>
      <param name="flashvars" value="RTMP=rtmp://<%=INFLUXIS_BASE%>dc3&file=usher-submission-thanks.flv&noServerDetect=true&availableControls=play,seek,volume&controls=auto&controlsPosition=bottom&volume=80&mute=false&autoPlay=true&aspect=letterbox&logo=&logoPosition=bottomLeft&logoScale=100&buffer=5&useDualBuffer=true&allowJSControl=true"></param>
    </object>
    -->
  </aside>
</div>

app/views/home/_user_videos.erb
<script id="user" type="text/html">
  <li>
    <h2><%= link_to "#{t :your_videos}", home_ajaxmyvideos_path(:format => 'js'), :remote => true, :class => 'reload_action', :disable_with => "#{t :reloading}" %></h2>
    <div id="ajaxmyvideos" class="video-list"></div>     
  </li>
</script>

app/views/home/ajaxmyvideos.erb
$("#ajaxmyvideos").html("<%= escape_javascript(render   :partial => 'shared/videolist',     :layout => false, :locals => { :videos => @my_videos, :flag => false })%>");

$('.img-overlay').hide();
  $('.imhover').mouseover(function(){
    $(this).find('.img-overlay').show();

  }).mouseout(function(){
    $(this).find('.img-overlay').hide();
  });

app/views/home/ajaxoldest.erb
$("#ajaxoldest").html("<%= escape_javascript(render   :partial => 'shared/videolist',     :layout => false, :locals => { :videos => @list_oldest, :flag => true })%>");

app/views/home/ajaxpopular.erb
$("#ajaxpopular").html("<%= escape_javascript(render   :partial => 'shared/videolist',     :layout => false, :locals => { :videos => @popular, :flag => false })%>");

app/views/home/ajaxrandom.erb
$("#ajaxrandom").html("<%= escape_javascript(render   :partial => 'shared/videolist',     :layout => false, :locals => { :videos => @list_random, :flag => false })%>");

app/views/home/bkup.index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<div id="load_battle" style="border-top:1px dotted #ccc;border-bottom:1px dotted #ccc;padding:8px 0">
  <%=render :partial => "shared/videobattle", :locals => { :videos => @battle,:flag => false  } %>
</div>

<div  style="clear:both;" id="error"></div>

<div  style="clear:both;">
  <%= link_to "reload", home_reloadbattle_path(:format => 'js'), :remote => true, :class => 'reload_action', :disable_with => 'reloading...' %></div>

<ul>
  
  <% cache do %>
    <li style="width:175px;float:left;margin:5px;padding:10px;border:1px solid #ccc;">
      <h3>latest</h3>
      <%@list_latest.each do |video| %>
        <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
      <%end%>
    </li>  
  <% end %>

  <% cache do %>
    <li style="width:175px;float:left;margin:5px;padding:10px;border:1px solid #ccc;">
      <h3>oldest</h3>
      <%@list_oldest.each do |video| %>
        <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
      <%end%>
    </li>
  <% end %>

  <% cache do %>
    <li style="width:175px;float:left;margin:5px;padding:10px;border:1px solid #ccc;">
      <h3>random</h3>
      <%@list_random.each do |video| %>
        <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
      <%end%>
    </li>
  <% end %>
  
  <!-- if there is a user and they have videos -->
  <% cache do %>
    <% if @user && @my_videos.count > 0%>
      <li style="width:175px;float:left;margin:5px;padding:10px;border:1px solid #ccc;">
        <h3>my videos</h3>
        <%@my_videos.each do |video| %>
          <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
        <%end%>
      </li>
    <% end %>
  <% end %>

  <% cache do %>
    <% if @user && @friendvideos%>
      <li style="width:175px;float:left;margin:5px;padding:10px;border:1px solid #ccc;">
        <h3>friends</h3>
        <%@friendvideos.each do |video| %>
          <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
        <%end%>      
      </li>
    <% end %>
  <% end %>
</ul>

app/views/home/index.html.erb
<div class="inner-wrapper">
  <div id="vid-nav-holder">
    <div class="vid-nav left">
      <%= link_to (t :reload), home_reloadbattle_path(:format => 'js'), :remote => true, :class => 'reload_action_left', :disable_with => "#{t :reloading}" %>
    </div>
    <div class="vid-nav right">
      <%= link_to (t :reload), home_reloadbattle_path(:format => 'js'), :remote => true, :class => 'reload_action', :disable_with => "#{t :reloading}" %>
    </div>
  </div>
  <div id="load_battle">
    <%=render :partial => "shared/videobattle", :locals => { :videos => @battle,:flag => false  } %>
  </div>

  

  

  <h1 class="choose-dancer-title"><%= t :list_title %></h1>
<div style="clear:both;" id="error"></div>
</div>


<div id="tab-area">
  <div class="inner-wrapper">
    <!-- Tabs -->
    <ul class="tabs">
      <li><a href="#"><%=t :popular_videos %></a></li>
      <% if @list_winner.count > 0 %>
      <li><a href="#"><%=t :winners_videos %></a></li>
      <% end %>
      <li><a href="#"><%=t :newest_videos %></a></li>
      <li class="auth"><%= link_to "#{t :your_videos}", home_ajaxmyvideos_path(:format => 'js'), :remote => true, :class => 'reload_action', :disable_with => "#{t :reloading}" %></li>
      <li class="auth"><%= link_to "#{t :friend_videos}", home_ajaxfreindvideos_path(:format => 'js'), :remote => true, :class => 'reload_action', :disable_with => "#{t :reloading}" %></li>
    </ul>


    </ul>
    <a href="/home/createvideo" class="tabs-rym"><%= t :auth_record_moves %></a>

    <!-- Tab content -->
    <div class="panes">
      <!-- Most Popular -->
      <div>
        <div class="video-list scrollable vertical">
          <div class="items">
          <% @list_popular.each_slice(12) do |video| -%>
            <div>
              <% video.each do |video| -%>
                <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
              <% end -%>
            </div>
          <%end -%>
          </div>
        </div> 
        <a href="#" class="load-down next"></a>
        <a href="#" class="load-up prev"></a>
      </div>

      <% if @is_winner.count > 0 %>
      <!-- Winners -->
      <div>
        <div class="video-list scrollable vertical">
          <div class="items">
          <% @list_winner.each_slice(12) do |video| -%>
            <div>
              <% video.each do |video| -%>
                <%=render :partial => "shared/videoblock", :locals => { :video => video }%>
              <% end -%>
            </div>
          <%end -%>
          </div>
        </div> 
        <a href="#" class="load-down next"></a>
        <a href="#" class="load-up prev"></a>
      </div>
      <% end %>

      <!-- Newest -->
      <div> 
        <div class="video-list scrollable vertical">
          <div class="items">
            <% @list_latest.each_slice(12) do |vid| -%>
              <div>
                <% vid.each do |v| %>
                  <%=render :partial => "shared/videoblock", :locals => { :video => v }%>
                <% end -%>
              </div>
            <% end -%>
          </div>
        </div> 
        <a href="#" class="load-down next"></a>
        <a href="#" class="load-up prev"></a>  
      </div>

      <!-- Your Videos -->
      <div id="ajaxmyvideos">
        
      </div>

      <!-- Friend's Videos -->
      <div id="ajaxfriendvideos">

      </div>

    </div>
  </div>
</div> <!-- END Tab area -->

app/views/home/mobile.html.erb
<%= render :partial => "shared/mobile_legal" %>
<div id="main">
  <header class="full-width">
    <div class="inner-wrap">
      <h1><%=t :cta_logo_title %></h1>
      <h2><span></span><%=t :cta_logo_caption %></h2>
      <div id="video-container">
        <% if session[:mobile_ipad] %>
          <%= image_tag('tablet/header-video.jpg', :class => 'video-overlay', :data => {:vid_id => "VFHcJxvI_t4", :player => "ytplayer"}, :size => '496x237') %>
        <% else %>
          <%= image_tag('mobile/header-video.jpg', :class => 'video-overlay', :data => {:vid_id => "VFHcJxvI_t4", :player => "ytplayer"}, :size => '284x182') %>
        <% end %>
        <div id="ytplayer"></div>
        <!-- <iframe width="284" height="182" src="https://www.youtube.com/embed/7tlA6LF4gCk?showinfo=0" frameborder="0" allowfullscreen></iframe> -->
      </div>
    </div>
  </header>
  <section id="share">
    <h1><%=t :mobile_share_header %></h1>
    <p><%=t :mobile_share_body %></p>
    <a class="ribbon" href="mailto:?subject=<%=t :mobile_email_subject %>&amp;body=<%=t :mobile_email_body %>"><%=t :mobile_share_link %></a>
    <div class="share-top">
      <span class="text"><%=t :share_text %></span>
      <%= render :partial => 'shared/social' %>
    </div>
  </section>
  <section id="featured" class="full-width">
    <div class="inner-wrap">
      <h1><%=t :mobile_featured_header %></h1>
      <div id="video-container" class='video-overlay' data-vid-id="jGuXGp72M84" data-player="ytplayer2">
        <% if session[:mobile_ipad] %>
          <%= image_tag('tablet/featured-overlay2.png', :data => {:vid_id => "jGuXGp72M84", :player => "ytplayer2"}, :size => '496x237') %>
        <% else %>
          <%= image_tag('mobile/featured-overlay2.png', :data => {:vid_id => "jGuXGp72M84", :player => "ytplayer2"}, :size => '284x182') %>
        <% end %>
        <p id="play-btn"><span></span><%=t :mobile_featured_video %></p>
        <!-- <iframe id="battle-vid" width="284" height="182" src="https://www.youtube.com/embed/7tlA6LF4gCk?showinfo=0" frameborder="0" allowfullscreen></iframe> -->
      </div>
      <div id="ytplayer2"></div>
      <h2><%=t :mobile_featured_sub_header %></h2>
      <p><%=t :mobile_featured_body %></p>
      <p class="second"><%=t :mobile_featured_body2 %></p>
    </div>
  </section>
  <section id="cta">
    <a class="ribbon" href="http://www.xbox.com/en-US/live/smartglass" target="_blank"><%=t :mobile_cta_learn_link %></a>
    <a class="learn" href="http://www.xbox.com/en-US/live/smartglass" target="_blank"><%=t :mobile_cta_learn_link2 %> &gt;</a>
    <div>
      <span></span>
      <a class="button first" href="http://marketplace.xbox.com/en-US/Product/Dance-Central-3/66acd000-77fe-1000-9115-d802373307d9" target="_blank"><span><%=t :mobile_cta_learn_link3 %></span></a>
      <a class="button" href="http://www.dancecentral.com/" target="_blank"><span><%=t :mobile_cta_learn_link4 %></span></a>
    </div>
  </section>
  <section id="sponsors" class="full-width">
    <div class="inner-wrap">
      <a href="<%=t :rating_link %>" id="rating" title=""><%= image_tag("#{t :mobile_rating_image}", :size => '119x53') %></s>
      <a id="smartglass" href="http://www.xbox.com/en-US/live/smartglass" target="_blank" title="smartglass">smartglass</a>
      <a id="harmonix" href="http://www.harmonixmusic.com/" target="_blank" title="harmonix">harmonix</a>
      <a id="xbox-360" href="http://www.xbox.com/Xbox360" target="_blank" title="xbox 360">xbox 360</a>
      <a id="kinect" href="http://www.xbox.com/kinect" target="_blank" title="kinect xbox 360">kinect</a>
      <a id="live" href="http://www.xbox.com/Live" target="_blank" title="xbox live">xbox live</a>
      <p>&copy; <%=t :legal_copy %></p>
    </div>
  </section>
  <footer class="full-width">
    <div class="inner-wrap">
      <a href="#" class="overlay-link first" data-link="#rules"><%=t :rules %></a>
      <a href="#" class="overlay-link" data-link="#faq" title="<%=t :faq_title %>"><%=t :faq %></a>
      <a href="http://privacy.microsoft.com/" target="_blank"><%=t :privacy %></a>
      <a href="#" class="overlay-link" data-link="#terms"><%=t :terms %></a>
    </div>
  </footer>
</div>

app/views/home/reloadbattle.js.erb
$("#load_battle").html("<%= escape_javascript(render :partial => 'shared/videobattle', :layout => false, :locals => { :auto_play => @auto_play, :videos => @battle, :flag => true })%>");

$("#user-block .user-block:odd").addClass('user-block-right');
$("#user-block .user-block:even").addClass('user-block-left');

app/views/home/rules.html.erb
<div class="inner-wrapper">
  <section role="faq" style="padding-bottom:230px;">
    <a href="/" class="go-back-btn">return to the dance off</a>
    <%= render :partial => "shared/rules" %>
  </section>
</div>

app/views/home/terms.html.erb
<div class="inner-wrapper">
  <section role="faq">
    <a href="/" class="go-back-btn"><%= t :return_to_the_dance_off %></a>
    <%= render :partial => "shared/terms" %>
  </section>
</div>

app/views/home/thanks.html.erb
<!-- do not use this, you probably want _thanks.html.erb -->
<h1>thanks for the upload</h1>
<p>Congratulations, your epic dance video uploaded successfully! It's off for moderation. Once it
passes the test you'll find it on the home page of the app underneath "My Videos."</p>

<a href="/videos/new">upload another video</a> | 
<a href="/">return to battles again</a>